// --- Chants data ---

const chants = {
"miserere-mei-deus": {
title: "Miserere Mei Deus",
image: "images/miserere.png",
audio: "audios/miserere.mp3",
pdf: "pdf/miserere.pdf",
video: "https://www.youtube.com/embed/H3v9unphfi0?si=AHNGc2T7oaFqO9ka", 
lyrics: [
"Miserere mei, Deus, secundum magnam misericordiam tuam.",
  "Et secundum multitudinem miserationum tuarum, dele iniquitatem meam.",
  "Amplius lava me ab iniquitate mea, et a peccato meo munda me.",
  "Quoniam iniquitatem meam ego cognosco, et peccatum meum contra me est semper.",
  "Tibi soli peccavi, et malum coram te feci,",
  "Ut justificeris in sermonibus tuis, et vincas cum judicaris.",
  "Ecce enim in iniquitatibus conceptus sum,",
  "Et in peccatis concepit me mater mea.",
  "Ecce enim veritatem dilexisti: incerta et occulta sapientiae tuae manifestasti mihi.",
  "Asperges me hyssopo, et mundabor; lavabis me, et super nivem dealbabor.",
  "Auditui meo dabis gaudium et laetitiam, et exsultabunt ossa humiliata.",
  "Averte faciem tuam a peccatis meis, et omnes iniquitates meas dele.",
  "Cor mundum crea in me, Deus, et spiritum rectum innova in visceribus meis.",
  "Ne projicias me a facie tua, et spiritum sanctum tuum ne auferas a me.",
  "Redde mihi laetitiam salutaris tui, et spiritu principali confirma me.",
  "Docebo iniquos vias tuas, et impii ad te convertentur.",
  "Libera me de sanguinibus, Deus, Deus salutis meae, et exsultabit lingua mea justitiam tuam.",
  "Domine, labia mea aperies, et os meum annuntiabit laudem tuam.",
  "Quoniam si voluisses sacrificium, dedissem utique: holocaustis non delectaberis.",
  "Sacrificium Deo spiritus contribulatus: cor contritum et humiliatum, Deus, non despicies.",
  "Benigne fac, Domine, in bona voluntate tua Sion, ut aedificentur muri Ierusalem.",
  "Tunc acceptabis sacrificium justitiae, oblationes et holocausta:",
  "Tunc imponent super altare tuum vitulos."
],
translation: [
"<strong>Miserere mei, Deus,</strong> Tem piedade de mim, ó Deus,",
"<strong>secundum magnam misericordiam tuam.</strong> Segundo a tua grande misericórdia.",
"<strong>Et secundum multitudinem miserationum tuarum,</strong> E conforme a abundância das tuas compaixões,",
"<strong>dele iniquitatem meam.</strong> Apaga a minha iniquidade.",
"<strong>Amplius lava me ab iniquitate mea,</strong> Lava-me completamente da minha culpa,",
"<strong>et a peccato meo munda me.</strong> E purifica-me do meu pecado.",
"<strong>Quoniam iniquitatem meam ego cognosco,</strong> Pois eu conheço a minha transgressão,",
"<strong>et peccatum meum contra me est semper.</strong> E o meu pecado está sempre diante de mim.",
"<strong>Tibi soli peccavi, et malum coram te feci,</strong> Pequei contra ti, contra ti somente,",
"<strong>ut justificeris in sermonibus tuis, et vincas cum judicaris.</strong> E fiz o que é mau diante dos teus olhos, para que sejas justo ao falares e puro ao julgares.",
"<strong>Ecce enim in iniquitatibus conceptus sum,</strong> Eu nasci na iniquidade,",
"<strong>et in peccatis concepit me mater mea.</strong> E em pecado me concebeu minha mãe.",
"<strong>Ecce enim veritatem dilexisti:</strong> Mas tu amas a verdade no íntimo,",
"<strong>incerta et occulta sapientiae tuae manifestasti mihi.</strong> E no oculto me fazes conhecer a sabedoria.",
"<strong>Asperges me hysopo, et mundabor;</strong> Purifica-me com o hissopo, e ficarei limpo;",
"<strong>lavabis me, et super nivem dealbabor.</strong> Lava-me, e ficarei mais branco que a neve.",
"<strong>Auditui meo dabis gaudium et laetitiam,</strong> Faz-me ouvir júbilo e alegria,",
"<strong>et exsultabunt ossa humiliata.</strong> E exultarão os ossos que esmagaste.",
"<strong>Averte faciem tuam a peccatis meis,</strong> Desvia o teu rosto dos meus pecados,",
"<strong>et omnes iniquitates meas dele.</strong> E apaga todas as minhas iniquidades.",
"<strong>Cor mundum crea in me, Deus,</strong> Cria em mim, ó Deus, um coração puro,",
"<strong>et spiritum rectum innova in visceribus meis.</strong> E renova dentro de mim um espírito reto.",
"<strong>Ne proiicias me a facie tua,</strong> Não me expulses da tua presença,",
"<strong>et spiritum sanctum tuum ne auferas a me.</strong> Nem retires de mim o teu Espírito Santo.",
"<strong>Redde mihi laetitiam salutaris tui,</strong> Devolve-me a alegria da tua salvação,",
"<strong>et spiritu principali confirma me.</strong> E sustenta-me com um espírito obediente.",
"<strong>Docebo iniquos vias tuas,</strong> Então ensinarei aos transgressores os teus caminhos,",
"<strong>et impii ad te convertentur.</strong> E os pecadores se converterão a ti.",
"<strong>Libera me de sanguinibus, Deus, Deus salutis meae,</strong> Livra-me da culpa de sangue, ó Deus, Deus da minha salvação,",
"<strong>et exsultabit lingua mea justitiam tuam.</strong> E a minha língua exaltará a tua justiça.",
"<strong>Domine, labia mea aperies,</strong> Senhor, abre os meus lábios,",
"<strong>et os meum annuntiabit laudem tuam.</strong> E a minha boca proclamará o teu louvor.",
"<strong>Quoniam si voluisses sacrificium, dedissem utique:</strong> Tu não te comprazes em sacrifícios, senão eu os daria;",
"<strong>holocaustis non delectaberis.</strong> Não te agradas de holocaustos.",
"<strong>Sacrificium Deo spiritus contribulatus:</strong> O sacrifício aceitável a Deus é o espírito quebrantado;",
"<strong>cor contritum, et humiliatum, Deus, non despicies.</strong> Um coração quebrantado e contrito, ó Deus, não desprezarás.",
"<strong>Benigne fac, Domine, in bona voluntate tua Sion,</strong> Faze o bem a Sião, segundo a tua boa vontade;",
"<strong>ut aedificentur muri Ierusalem.</strong> Edifica os muros de Jerusalém.",
"<strong>Tunc acceptabis sacrificium justitiae, oblationes et holocausta:</strong> Então te agradarás dos sacrifícios de justiça, das ofertas queimadas e holocaustos;",
"<strong>tunc imponent super altare tuum vitulos.</strong> Então novilhos serão oferecidos sobre o teu altar."
],

history: [
"<em>Miserere mei, Deus</em>, o Salmo 50, é um dos salmos penitenciais mais profundos e comoventes da tradição cristã.", "Ele expressa um arrependimento sincero diante de Deus, sendo frequentemente cantado em canto gregoriano, especialmente durante a Quaresma e na liturgia das Laudes das sextas-feiras.", "É também conhecido pela sua versão musical mais célebre, o 'Miserere' de Gregorio Allegri, composta no século XVII para a Capela Sistina.", "Essa obra se tornou símbolo de beleza sacra e arrependimento profundo, com passagens celestiais que refletem a esperança de purificação."
]
},

"anima-christi": {
title: "Anima Christi",
image: "images/anima-christi.png",
audio: "audios/anima-christi.mp3",
pdf: "pdf/anima-christi.pdf",
video: "https://www.youtube.com/embed/vOBP7l3PDNo", 
lyrics: [
"Anima Christi, sanctifica me.",
"Corpus Christi, salva me.",
"Sanguis Christi, inebria me.",
"Aqua lateris Christi, lava me.",
"Passio Christi, conforta me.",
"O bone Jesu, exaudi me.",
"Intra tua vulnera absconde me.",
"Ne permittas me separari a te.",
"Ab hoste maligno defende me.",
"In hora mortis meae voca me.",
"Et iube me venire ad te,",
"Ut cum Sanctis tuis laudem te.",
"In saecula saeculorum.",
"Amen"
],
translation: [
"Alma de Cristo, santifica-me.",
"Corpus Christi, salva-me.",
"Sangue de Cristo, inebria-me.",
"Água do lado de Cristo, lava-me.",
"Paixão de Cristo, fortalece-me.",
"Ó bom Jesus, ouça-me.",
"Esconde-me dentro de tuas feridas.",
"Não permitas que eu me separe de ti.",
"Proteja-me do inimigo maligno.",
"Na hora da minha morte, chama-me.",
"E me mande ir até você,",
"Para que eu te louve com os teus santos.",
"Para sempre e sempre.",
"Amém"
],
history: [
"<em>Anima Christi</em> (do seu incipit, Latim para 'Alma de Cristo') é uma oração Católica cuja redação final é tradicionalmente datada do final do século XIII ou início do século XIV, com autoria incerta, embora popularmente atribuída ao Papa João XXII.",

"A oração é usada principalmente na espiritualidade católica, como uma devoção pessoal, meditação sobre a Paixão de Cristo e a Eucaristia, e frequentemente como preparação ou ação de graças após a recepção da Sagrada Comunhão.",

"Ao longo dos séculos, a devoção popular tem difundido a oração, sendo utilizada em novenas, retiros espirituais e outras práticas piedosas focadas na Paixão de Cristo. Sua recitação não está especificamente ligada a um dia do ano para concessão de indulgências da mesma forma que o Te Deum, mas sua importância reside na profunda conexão espiritual com os mistérios da fé.",

"O hino/oração é encontrado também na hinódia ou práticas litúrgicas de outras igrejas cristãs, embora com menor frequência e destaque do que na tradição católica, refletindo a universalidade dos temas da Paixão e da união com Cristo.",
]
},

"de-pacem-domine": {
title: "De Pacem, Domine",
image: "images/de-pacem-domine.png",
audio: "audios/de-pacem-domine.mp3",
pdf: "pdf/de-pacem-domine.pdf",
video: "https://www.youtube.com/embed/1zLNa4Zyet4?si=ZvgJk7yuuTzBLFFx", 
lyrics: [
"Da pacem, Domine,",
  "Da pacem, Domine, in diebus nostris",
  "Quia non est alius",
  "Qui pugnet pro nobis",
  "Nisi Tu Deus noster",
  "Fiat pax in virtute tua: Et abundantia in turribus tuis",
  "Da pacem, Domine, in diebus nostris",
  "Quia non est alius",
  "Qui pugnet pro nobis",
  "Nisi Tu Deus noster",
  "Propter fratres meos et proximos meos loquebar pacem de te",
  "Da pacem, Domine, in diebus nostris",
  "Quia non est alius",
  "Qui pugnet pro nobis",
  "Nisi Tu Deus noster",
  "Propter domum Domini Dei nostri quaesivi bona tibi",
  "Da pacem, Domine, in diebus nostris",
  "Quia non est alius",
  "Qui pugnet pro nobis",
  "Nisi Tu Deus noster",
  "Rogate quae ad pacem sunt Jerusalem: Et abundantia diligentibus te",
  "Da pacem, Domine, in diebus nostris",
  "Quia non est alius",
  "Qui pugnet pro nobis",
  "Nisi Tu Deus noster",
  "Gloria Patri et Filio et Spiritui Sancto",
  "Sicut erat in principio et nunc et semper, et in saecula saeculorum",
  "Amen"
],
translation: [
"Dai a paz, Senhor,",
  "Dai a paz, Senhor, em nossos dias,",
  "Porque não há outro",
  "Que lute por nós",
  "Senão Tu, nosso Deus.",
  "Haja paz em teu poder: E abundância em tuas torres.",
  "Dai a paz, Senhor, em nossos dias,",
  "Porque não há outro",
  "Que lute por nós",
  "Senão Tu, nosso Deus.",
  "Por causa de meus irmãos e meus próximos, falava eu: Paz esteja em ti.",
  "Dai a paz, Senhor, em nossos dias,",
  "Porque não há outro",
  "Que lute por nós",
  "Senão Tu, nosso Deus.",
  "Por amor da casa do Senhor nosso Deus, procuro o teu bem.",
  "Dai a paz, Senhor, em nossos dias,",
  "Porque não há outro",
  "Que lute por nós",
  "Senão Tu, nosso Deus.",
  "Orai pela paz de Jerusalém: E haja abundância para os que te amam.",
  "Dai a paz, Senhor, em nossos dias,",
  "Porque não há outro",
  "Que lute por nós",
  "Senão Tu, nosso Deus.",
  "Glória ao Pai e ao Filho e ao Espírito Santo,",
  "Assim como era no princípio, agora e sempre, e por todos os séculos dos séculos.",
  "Amém."
],
history: [
"<em>De Pacem, Domine</em> (do seu incipit, Latim para 'Dai a Paz, Senhor') é um canto gregoriano cuja origem exata não é precisamente datada, mas é amplamente associado ao período medieval, inserido no contexto das súplicas por paz, especialmente em tempos de conflito e incerteza.", "O hino é usado principalmente na liturgia católica, como um canto de súplica pela paz, frequentemente entoado durante a Missa, especialmente em momentos de oração pela paz mundial ou em situações de aflição. Sua estrutura repetitiva e melodia contemplativa reforçam o pedido constante pela paz divina.", "Ao longo da história, a simplicidade e a profundidade da sua mensagem fizeram com que este canto fosse adotado em diversas ocasiões litúrgicas e paralitúrgicas, tornando-se uma expressão musical da busca humana pela tranquilidade e harmonia concedidas por Deus.", "O canto é encontrado também em diversas coletâneas de cantos gregorianos, sendo um exemplo clássico do repertório tradicional da Igreja Católica e, por sua temática universal, pode ressoar em contextos de oração pela paz em outras tradições cristãs."
]
},

"litaniae-sanctorum": {
title: "Litaniae Sanctorum",
image: "images/litaniae-sanctorum.png",
audio: "audios/litaniae-sanctorum.mp3",
pdf: "pdf/litaniae-sanctorum.pdf",
video: "https://www.youtube.com/embed/1zLNa4Zyet4?si=ZvgJk7yuuTzBLFFx", 
lyrics: [
"Kyrie, eleison.",
  "Christe, eleison.",
  "Kyrie, eleison.",
  "Christe, audi nos.",
  "Christe, exaudi nos.",

  "Pater de caelis, Deus,",
  "Fili, Redemptor mundi, Deus,",
  "Spiritus Sancte, Deus,",
  "Sancta Trinitas, unus Deus,",

  "Sancta Maria,",
  "Sancta Dei Genetrix,",
  "Sancta Virgo virginum,",

  "Sancte Michael,",
  "Sancte Gabriel,",
  "Sancte Raphael,",
  "Omnes sancti Angeli et Archangeli,",
  "Omnes sancti beatorum spirituum ordines,",

  "Sancte Ioannes Baptista,",
  "Sancte Ioseph,",
  "Omnes sancti Patriarchae et Prophetae,",

  "Sancte Petre,",
  "Sancte Paule,",
  "Sancte Andrea,",
  "Sancte Iacobe,",
  "Sancte Ioannes,",
  "Sancte Thoma,",
  "Sancte Philippe,",
  "Sancte Bartholomaee,",
  "Sancte Matthae,",
  "Sancte Simon,",
  "Sancte Thaddaee,",
  "Sancte Mathia,",
  "Sancte Barnaba,",
  "Sancte Luca,",
  "Sancte Marce,",
  "Omnes sancti Apostoli et Evangelistae,",
  "Omnes sancti Discipuli Domini,",

  "Sancte Stephane,",
  "Sancte Laurenti,",
  "Sancte Vincenti,",
  "Sancte Fabiane et Sancte Sebastiane,",
  "Sancte Ioannes et Sancte Paule,",
  "Sancte Cosma et Sancte Damiane,",
  "Omnes sancti Martyres,",

  "Sancte Silvester,",
  "Sancte Gregori,",
  "Sancte Ambrosi,",
  "Sancte Augustine,",
  "Sancte Hieronyme,",
  "Sancte Martine,",
  "Sancte Nicolae,",
  "Omnes sancti Pontifices et Confessores,",
  "Omnes sancti Doctores,",

  "Sancte Antoni,",
  "Sancte Benedicte,",
  "Sancte Bernarde,",
  "Sancte Dominice,",
  "Sancte Francisce,",
  "Omnes sancti Sacerdotes et Levitae,",
  "Omnes sancti Monachi et Eremitae,",

  "Sancta Maria Magdalena,",
  "Sancta Agatha,",
  "Sancta Lucia,",
  "Sancta Agnes,",
  "Sancta Caecilia,",
  "Sancta Anastasia,",
  "Omnes sanctae Virgines et Viduae,",
  "Omnes Sancti et Sanctae Dei,",

  "Propitius esto,",
  "Parce nobis, Domine.",
  "Propitius esto,",
  "Exaudi nos, Domine.",

  "Ab omni malo,",
  "Ab omni peccato,",
  "Ab ira tua,",
  "A morte perpetua,",
  "Ab insidiis diaboli,",
  "Ab ira et odio et omni mala voluntate,",
  "A spiritu fornicationis,",
  "A fulgure et tempestate,",
  "A flagello terraemotus,",
  "A peste, fame et bello,",
  "Ab omni malo,",

  "Per mysterium sanctae Incarnationis tuae,",
  "Per adventum tuum,",
  "Per nativitatem tuam,",
  "Per baptismum et sanctum ieiunium tuum,",
  "Per crucem et passionem tuam,",
  "Per mortem et sepulturam tuam,",
  "Per sanctam resurrectionem tuam,",
  "Per admirabilem ascensionem tuam,",
  "Per adventum Spiritus Sancti Paracliti,",
  "In die iudicii,",

  "Peccatores,",
  "Te rogamus, audi nos.",
  "Ut nobis parcas,",
  "Te rogamus, audi nos.",
  "Ut nobis indulgeas,",
  "Te rogamus, audi nos.",
  "Ut ad veram paenitentiam nos perducas,",
  "Te rogamus, audi nos.",
  "Ut Ecclesiam tuam sanctam regere et conservare digneris,",
  "Te rogamus, audi nos.",
  "Ut domnum Apostolicum et omnes ecclesiasticos ordines in sancta religione conserves,",
  "Te rogamus, audi nos.",
  "Ut inimicos sanctae Ecclesiae humiliare digneris,",
  "Te rogamus, audi nos.",
  "Ut regibus et principibus christianis pacem et veram concordiam dones,",
  "Te rogamus, audi nos.",
  "Ut cuncto populo christiano pacem et unitatem largiri digneris,",
  "Te rogamus, audi nos.",
  "Ut omnes errantes ad unitatem Ecclesiae revocare et infideles ad Evangelii lumen perducere digneris,",
  "Te rogamus, audi nos.",
  "Ut nosmetipsos in tuo sancto servitio confortare et conservare digneris,",
  "Te rogamus, audi nos.",
  "Ut mentes nostras ad caelestia desideria erigas,",
  "Te rogamus, audi nos.",
  "Ut omnibus benefactoribus nostris sempiterna bona retribuas,",
  "Te rogamus, audi nos.",
  "Ut animas nostras, fratrum, propinquorum et benefactorum nostrorum ab aeterna damnatione eripias,",
  "Te rogamus, audi nos.",
  "Ut fructus terrae dare et conservare digneris,",
  "Te rogamus, audi nos.",
  "Ut omnibus fidelibus defunctis requiem aeternam dones,",
  "Te rogamus, audi nos.",
  "Ut nos exaudire digneris,",
  "Te rogamus, audi nos.",

  "Fili Dei,",
  "Te rogamus, audi nos.",

  "Agnus Dei, qui tollis peccata mundi,",
  "Parce nobis, Domine.",
  "Agnus Dei, qui tollis peccata mundi,",
  "Exaudi nos, Domine.",
  "Agnus Dei, qui tollis peccata mundi,",
  "Miserere nobis.",

  "Christe, audi nos.",
  "Christe, exaudi nos.",
  "Kyrie, eleison.",
  "Christe, eleison.",
  "Kyrie, eleison."
],
translation: [
"Senhor, tende piedade de nós.",
  "Cristo, tende piedade de nós.",
  "Senhor, tende piedade de nós.",
  "Cristo, ouvi-nos.",
  "Cristo, atendei-nos.",

  "Pai do céu, que sois Deus,",
  "Filho, Redentor do mundo, que sois Deus,",
  "Espírito Santo, que sois Deus,",
  "Santíssima Trindade, um só Deus,",

  "Santa Maria,",
  "Santa Mãe de Deus,",
  "Santa Virgem das virgens,",

  "São Miguel,",
  "São Gabriel,",
  "São Rafael,",
  "Todos os santos Anjos e Arcanjos,",
  "Todas as santas ordens dos espíritos bem-aventurados,",

  "São João Batista,",
  "São José,",
  "Todos os santos Patriarcas e Profetas,",

  "São Pedro,",
  "São Paulo,",
  "Santo André,",
  "São Tiago,",
  "São João,",
  "São Tomé,",
  "São Filipe,",
  "São Bartolomeu,",
  "São Mateus,",
  "São Simão,",
  "São Tadeu,",
  "São Matias,",
  "São Barnabé,",
  "São Lucas,",
  "São Marcos,",
  "Todos os santos Apóstolos e Evangelistas,",
  "Todos os santos Discípulos do Senhor,",

  "Santo Estêvão,",
  "São Lourenço,",
  "São Vicente,",
  "São Fabiano e São Sebastião,",
  "São João e São Paulo,",
  "São Cosme e São Damião,",
  "Todos os santos Mártires,",

  "São Silvestre,",
  "São Gregório,",
  "Santo Ambrósio,",
  "Santo Agostinho,",
  "São Jerônimo,",
  "São Martinho,",
  "São Nicolau,",
  "Todos os santos Pontífices e Confessores,",
  "Todos os santos Doutores,",

  "Santo Antônio,",
  "São Bento,",
  "São Bernardo,",
  "São Domingos,",
  "São Francisco,",
  "Todos os santos Sacerdotes e Levitas,",
  "Todos os santos Monges e Eremitas,",

  "Santa Maria Madalena,",
  "Santa Ágata,",
  "Santa Luzia,",
  "Santa Inês,",
  "Santa Cecília,",
  "Santa Anastácia,",
  "Todas as santas Virgens e Viúvas,",
  "Todos os Santos e Santas de Deus,",

  "Sede propício,",
  "Perdoai-nos, Senhor.",
  "Sede propício,",
  "Atendei-nos, Senhor.",

  "De todo o mal,",
  "De todo o pecado,",
  "Da vossa ira,",
  "Da morte eterna,",
  "Das ciladas do demônio,",
  "Da ira, do ódio e de toda má vontade,",
  "Do espírito da impureza,",
  "Do raio e da tempestade,",
  "Do flagelo do terremoto,",
  "Da peste, da fome e da guerra,",
  "De todo o mal,",

  "Pelo mistério da vossa santa Encarnação,",
  "Pela vossa vinda,",
  "Pelo vosso nascimento,",
  "Pelo vosso batismo e santo jejum,",
  "Pela vossa cruz e paixão,",
  "Pela vossa morte e sepultura,",
  "Pela vossa santa ressurreição,",
  "Pela vossa admirável ascensão,",
  "Pela vinda do Espírito Santo Paráclito,",
  "No dia do juízo,",

  "Pecadores que somos,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que nos perdoeis,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que nos sejais indulgente,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que nos conduzis à verdadeira penitência,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis reger e conservar a vossa santa Igreja,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que conserveis na santa religião o Senhor Papa e todas as ordens eclesiásticas,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis humilhar os inimigos da santa Igreja,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que deis aos reis e príncipes cristãos a paz e a verdadeira concórdia,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis conceder a todo o povo cristão a paz e a unidade,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis reconduzir à unidade da Igreja todos os que erram e levar os infiéis à luz do Evangelho,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis confortar-nos e conservar-nos no vosso santo serviço,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que eleveis as nossas mentes aos desejos celestiais,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que recompenseis com bens sempiternos todos os nossos benfeitores,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que livreis da eterna danação as nossas almas, as de nossos irmãos, parentes e benfeitores,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis dar e conservar os frutos da terra,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que deis a todos os fiéis defuntos o eterno descanso,",
  "Nós vos rogamos, ouvi-nos.",
  "Para que vos digneis atender-nos,",
  "Nós vos rogamos, ouvi-nos.",

  "Filho de Deus,",
  "Nós vos rogamos, ouvi-nos.",

  "Cordeiro de Deus, que tirais os pecados do mundo,",
  "Perdoai-nos, Senhor.",
  "Cordeiro de Deus, que tirais os pecados do mundo,",
  "Atendei-nos, Senhor.",
  "Cordeiro de Deus, que tirais os pecados do mundo,",
  "Tende piedade de nós.",

  "Cristo, ouvi-nos.",
  "Cristo, atendei-nos.",
  "Senhor, tende piedade de nós.",
  "Cristo, tende piedade de nós.",
  "Senhor, tende piedade de nós."
],
history: [
 "A <em>'Litaniae Sanctorum'</em> (Ladainha dos Santos) é uma antiga e venerável oração litúrgica da Igreja Católica, com raízes que remontam aos primeiros séculos do cristianismo. Sua forma atual evoluiu gradualmente ao longo do tempo.", "A 'Litaniae Sanctorum' como a conhecemos hoje começou a tomar forma por volta do século VII, com a inclusão de invocações a santos específicos. O Papa São Gregório Magno (c. 540-604) é frequentemente associado à sua organização e popularização, embora a ladainha continue a se desenvolver após seu pontificado.", "Historicamente, a Ladainha dos Santos tem sido usada em uma variedade de contextos litúrgicos importantes, incluindo a Vigília Pascal (onde ocupa um lugar de destaque), as procissões, as ordenações sacerdotais e episcopais, as consagrações de igrejas e altares, e em tempos de grande necessidade ou penitência pública."
]
},

"te-deum": {
title: "Te Deum",
image: "images/deus.png",
audio: "audios/te-deum.mp3",
pdf: "pdf/te-deum.pdf",
video: "https://www.youtube.com/embed/HAWkoXNHvkw?si=imQ_GXRtQQSEW2T5",
lyrics: [
  "Te Deum laudamus: te Dominum confitemur.",
  "Te aeternum Patrem omnis terra veneratur.",
  "Tibi omnes Angeli; tibi caeli et universae Potestates;",
  "Tibi Cherubim et Seraphim incessabili voce proclamant:",
  "Sanctus, Sanctus, Sanctus, Dominus Deus Sabaoth.",
  "Pleni sunt caeli et terra maiestatis gloriae tuae.",
  "Te gloriosus Apostolorum chorus,",
  "Te Prophetarum laudabilis numerus,",
  "Te Martyrum candidatus laudat exercitus.",
  "Te per orbem terrarum sancta confitetur Ecclesia, Patrem immensae maiestatis:",
  "Venerandum tuum verum et unicum Filium;",
  "Sanctum quoque Paraclitum Spiritum.",
  "Tu Rex gloriae, Christe.",
  "Tu Patris sempiternus es Filius.",
  "Tu ad liberandum suscepturus hominem,",
  "non horruisti Virginis uterum.",
  "Tu, devicto mortis aculeo,",
  "aperuisti credentibus regna caelorum.",
  "Tu ad dexteram Dei sedes, in gloria Patris.",
  "Iudex crederis esse venturus.",
  "Te ergo quaesumus, tuis famulis subveni:",
  "quos pretioso sanguine redemisti.",
  "Aeterna fac cum sanctis tuis in gloria numerari.",
  "Salvum fac populum tuum, Domine, et benedic hereditati tuae.",
  "Et rege eos, et extolle illos usque in aeternum.",
  "Per singulos dies benedicimus te;",
  "Et laudamus Nomen tuum in saeculum, et in saeculum saeculi.",
  "Dignare, Domine, die isto sine peccato nos custodire.",
  "Miserere nostri Domine, miserere nostri.",
  "Fiat misericordia tua, Domine, super nos, quemadmodum speravimus in te.",
  "In te, Domine, speravi: non confundar in aeternum."
],
translation: [
  "A Vós, ó Deus, louvamos; a Vós, Senhor, confessamos.",
  "A Vós, eterno Pai, venera toda a terra.",
  "A Vós louvam todos os Anjos; a Vós os Céus e todas as Potestades.",
  "A Vós os Querubins e Serafins com incessante voz proclamam:",
  "Santo, Santo, Santo, Senhor Deus dos Exércitos.",
  "Cheios estão os céus e a terra da majestade da vossa glória.",
  "A Vós louva o glorioso coro dos Apóstolos,",
  "A Vós o louvável número dos Profetas,",
  "A Vós louva o exército resplandecente dos Mártires.",
  "A Vós a Santa Igreja confessa por todo o orbe, ó Pai de imensa majestade:",
  "Vosso verdadeiro e único Filho, digno de adoração;",
  "E também o Espírito Santo, Consolador.",
  "Vós sois o Rei da glória, ó Cristo.",
  "Vós sois o Filho eterno do Pai.",
  "Vós, para libertar o homem, assumistes a condição humana,",
  "sem horror do seio da Virgem.",
  "Vós, vencendo o aguilhão da morte,",
  "abristes aos fiéis o reino dos céus.",
  "Vós estais sentado à direita de Deus, na glória do Pai.",
  "Cremos que de lá vireis a julgar os vivos e os mortos.",
  "A Vós, pois, suplicamos, ajudai os vossos servos:",
  "que remistes com vosso precioso sangue.",
  "Fazei que sejamos contados entre os vossos santos na glória eterna.",
  "Salvai o vosso povo, Senhor, e abençoai a vossa herança.",
  "Governai-os e exaltai-os eternamente.",
  "Todos os dias vos bendizemos;",
  "E louvamos o vosso nome pelos séculos dos séculos.",
  "Dignai-vos, Senhor, neste dia, livrar-nos do pecado.",
  "Tende misericórdia de nós, Senhor, tende misericórdia de nós.",
  "Venha sobre nós, Senhor, a vossa misericórdia, como em vós esperámos.",
  "Em Vós, Senhor, esperei: não serei confundido eternamente."
],
history: [
"Te Deum (do seu incipit, <em>Te Deum Laudamus</em>, Latim para 'a Vós, ó Deus, louvamos') é um hino Católico cuja redação final é tradicionalmente datada do ano 387 d.C. quando da ocasião do batismo de Santo Agostinho por Santo Ambrósio, mas de origem ancestral, com autoria rastreada ao Papa Santo Aniceto, em 160 d.C.", "O hino é usado principalmente na liturgia católica, como parte do Ofício de Leituras da Liturgia das Horas e outros eventos solenes de ações de graças.", "No último dia do ano, as leis eclesiásticas concedem aos católicos a indulgência plenária, nas condições usuais, se estes recitarem um Te Deum em público no réveillon como gratidão a Deus pelos benefícios Dele recebidos durante o ano que finda.", "O hino é encontrado também na hinódia ou práticas litúrgicas de outras igrejas cristãs, incluindo o Livro de Oração Comum da Igreja Anglicana, as matinas luteranas e, de modo menos regular, em outras denominações protestantes e evangélicas."
]
},

"credo-iii": {
title: "Credo III",
image: "images/credo.png",
audio: "audios/credo-iii.mp3",
pdf: "pdf/credo-iii.pdf",
video: "https://www.youtube.com/embed/kk-OBG44Qu8?si=tyskbEI6eHBvA7SE",
lyrics: [
"Credo in unum Deum.",
"Patrem omnipoténtem, factórem cæli et terræ,",
"visibílium ómnium et invisibílium.",
"Et in unum Dóminum Iesum Christum,",
"Fílium Dei Unigénitum,",
"et ex Patre natum ante ómnia sæcula.",
"Deum de Deo, lumen de lúmine, Deum verum de Deo vero.",
"Génitum, non factum, consubstantiálem Patri:",
"per quem ómnia facta sunt.",
"Qui propter nos hómines et propter nostram salútem descéndit de cælis.",
"Et incarnátus est de Spíritu Sancto ex María Vírgine, et homo factus est.",
"Crucifíxus étiam pro nobis sub Póntio Piláto;",
"passus et sepúltus est,",
"et resurréxit tértia die, secúndum Scriptúras,",
"et ascéndit in cælum, sedet ad déxteram Patris.",
"Et íterum ventúrus est cum glória, iudicáre vivos et mórtuos,",
"cuius regni non erit finis.",
"Et in Spíritum Sanctum, Dóminum et vivificántem: qui ex Patre Filióque procédit.",
"Qui cum Patre et Fílio simul adorátur et conglorificátur: qui locútus est per prophétas.",
"Et unam, sanctam, cathólicam et apostólicam Ecclésiam.",
"Confíteor unum baptísma in remissiónem peccatórum.",
"Et exspécto resurrectiónem mortuórum, et vitam ventúri sæculi. Amen."
],
translation: [
"Creio em um só Deus,",
"Pai todo-poderoso, criador do céu e da terra,",
"de todas as coisas visíveis e invisíveis.",
"Creio em um só Senhor, Jesus Cristo,",
"Filho unigênito de Deus,",
"nascido do Pai antes de todos os séculos:",
"Deus de Deus, luz da luz, Deus verdadeiro de Deus verdadeiro,",
"gerado, não criado, consubstancial ao Pai.",
"Por Ele todas as coisas foram feitas.",
"Por nós, homens, e para a nossa salvação desceu dos céus.",
"E se encarnou pelo Espírito Santo no seio da Virgem Maria, e se fez homem.",
"Também por nós foi crucificado sob Pôncio Pilatos,",
"padeceu e foi sepultado",
"e ressuscitou ao terceiro dia, conforme as Escrituras;",
"e subiu aos céus, está sentado à direita do Pai.",
"De novo há de vir, em sua glória, para julgar os vivos e os mortos;",
"e o seu Reino não terá fim.",
"Creio no Espírito Santo, Senhor que dá a vida, e procede do Pai e do Filho.",
"Com o Pai e o Filho é adorado e glorificado: Ele que falou pelos profetas.",
"Creio na Igreja, una, santa, católica e apostólica.",
"Professo um só batismo para a remissão dos pecados.",
"Espero a ressurreição dos mortos e a vida do mundo que há de vir. Amém."
],

history: [
"O <strong>Credo III</strong> é uma das versões gregorianas mais tradicionais do símbolo da fé católica, utilizado especialmente em missas solenes do rito romano. Sua melodia simples e solene facilita a participação de toda a assembleia, o que reforça seu papel comunitário na liturgia.",
"Este canto recita o <em>Credo Niceno-Constantinopolitano</em>, formulado nos Concílios de Niceia (325) e Constantinopla (381), como resposta às heresias cristológicas da época. O texto proclama a fé na Trindade, na encarnação do Verbo, na Igreja e na vida eterna.",
"O uso do Credo cantado é incentivado especialmente em domingos e solenidades. Entre as diversas melodias existentes no repertório gregoriano, o Credo III se destaca por seu equilíbrio entre beleza melódica e facilidade de execução, sendo uma das versões mais utilizadas ao longo do ano litúrgico.",
"Ele expressa, em forma de oração solene, a unidade da fé cristã professada por fiéis de todos os tempos, sendo um dos pilares musicais do <em>Ordinarium Missae</em>, ao lado do Kyrie, Gloria, Sanctus e Agnus Dei."
]
}
};